### ISSUE TITLE
Relative Paths

### ISSUE THREAD

**Issue by informaterian** [Fightbackman/server-scripts#14]
Beim Ausführen des Scripts `install_mailserver.sh` auf folgende weiße `mailserver/install_mailserver.sh` sind innerhalb des Scripts die Pfade zu Unterprogrammen aus anderen Ordnern falsch.

**Comment by Fightbackman** [comment]
Hat du Zeilenangaben? Dann kümmere ich mich darum.

**Comment by Fightbackman** [comment]
Also ich hab alle relativen Pfade gerade überprüft.
Die scheinen  zu stimmen.
