### ISSUE TITLE
letsencrypt / neue config gernerieren

### ISSUE THREAD

**Issue by informaterian** [Fightbackman/server-scripts#18]
Ein Skript muss erstellt werden um
für bestimmte Domains neue config files zu generieren.

**Comment by Fightbackman** [comment]
So hab das mal erledigt.[https://github.com/Fightbackman/server-scripts/commit/fcfb3719e6104e3acfbb812c08c137ee57231cba]
@informaterian hattest du iwo direkt auf das letsencrypt skript verwiesen?
Wenn ja muss man mal schauen, ob das dann noch so passt.

**Comment by informaterian** [comment]
Meinst du das install_letsencrypt?
