### ISSUE TITLE
install_mailserver.sh/ software installation / read

### ISSUE THREAD

**Issue by Fightbackman** [Fightbackman/server-scripts#35]
Was soll das read immer nach dem echo in der zweiten Zeile nach jeder if abfrage am Anfang des Scripts? @informaterian

**Comment by informaterian** [comment]
Das war nur für mich um zwischenzeitlich zu wissen was grade überhaupt abgeht und wo er im script jetzt ist.
Da findet man leichter heraus ob eine if oder so nicht funktioniert hat :)

**Comment by Fightbackman** [comment]
Ok ich hab das jetzt mal rausgenommen.
