### ISSUE TITLE
docker.sh

### ISSUE THREAD

**Issue by informaterian** [Fightbackman/server-scripts#6]
sudo sh -c "echo \"deb https://apt.dockerproject.org/repo debian-jessie main >> /etc/apt/sources.list.d/docker.list\""; #hier kommen misterioese probleme auf

**Comment by Fightbackman** [comment]
Sollte gelöst sein.
Siehe https://github.com/Fightbackman/server-scripts/commit/722586a31099f4dfd58527f67ce4a58b7c37938a
